CryptoApp/CryptoApp/CryptoApp/Models/ErrorViewModel.cs
using System;

namespace CryptoApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CryptoApp/CryptoApp/CryptoApp/Controllers/EncryptController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using CryptoApp.Services.Encryption;
using CryptoApp.Services.Files;
using CryptoApp.Services.Files.Impl;
using Microsoft.AspNetCore.Http;

namespace CryptoApp.Controllers
{
    [Controller]
    [Route("crypto")]
    public class EncryptController : Controller
    {
        private IKeyTextEncryptor _encryptor;
        private TxtFileService _txtFileService;
        private DocxFileService _docxFileService;

        public EncryptController(
            IKeyTextEncryptor encryptor, 
            TxtFileService txtFileService, DocxFileService docxFileService)
        {
            _encryptor = encryptor;
            _txtFileService = txtFileService;
            _docxFileService = docxFileService;
        }

        [HttpGet("load_file")]
        public IActionResult LoadFileForm()
        {
            return View("LoadFileForm");
        }

        [HttpPost("encrypt")]
        public IActionResult Encrypt(IFormFile file, string cipherKey, string lang)
        {
            Language language = GetLanguage(lang);
            ITextFileService service = GetSuitableFileService(file);

            string text = GetFileRawText(file, service);
            string encryptedText = _encryptor.Encrypt(text, cipherKey, language);
            byte[] responseFileData = service.CreateFileFromString(encryptedText);

            string fileFormat = file.FileName.Substring(file.FileName.LastIndexOf('.'));

            return File(responseFileData, "text/plain", $"{Guid.NewGuid()}{fileFormat}");
        }

        [HttpPost("decrypt")]
        public IActionResult Decrypt(IFormFile file, string cipherKey, string lang)
        {
            Language language = GetLanguage(lang);
            ITextFileService service = GetSuitableFileService(file);

            string text = GetFileRawText(file, service);
            string decryptedText = _encryptor.Decrypt(text, cipherKey, language);
            byte[] responseFileData = service.CreateFileFromString(decryptedText);

            string fileFormat = file.FileName.Substring(file.FileName.LastIndexOf('.'));

            return File(responseFileData, "text/plain", $"{Guid.NewGuid()}{fileFormat}");
        }

        [NonAction]
        private string GetFileRawText(IFormFile file, ITextFileService service)
        {
            using Stream fileStream = file.OpenReadStream();
            using MemoryStream memoryStream = new MemoryStream();

            fileStream.CopyTo(memoryStream);
            memoryStream.Seek(0, SeekOrigin.Begin);

            return service.ReadRawText(memoryStream.ToArray());
        }

        [NonAction]
        private Language GetLanguage(string lang)
        {
            if (lang == "RU")
                return Language.Rus;
            return Language.Eng;
        }

        [NonAction]
        private ITextFileService GetSuitableFileService(IFormFile file)
        {
            if (file.FileName.EndsWith(".txt"))
                return _txtFileService;

            if (file.FileName.EndsWith(".docx"))
                return _docxFileService;

            throw new ArgumentException($"type of file {file.FileName} not supported");
        }
    }
}

CryptoApp/CryptoApp/CryptoApp/Controllers/HomeController.cs
using CryptoApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace CryptoApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CryptoApp/CryptoApp/CryptoApp/Views/Encrypt/LoadFileForm.cshtml
@{
    ViewData["Title"] = "Encryption & decryption";
}

<style>
    .center {
        position:absolute;
        top:50%;
        left:50%;
        padding:10px;
        -ms-transform: translateX(-50%) translateY(-50%);
        -webkit-transform: translate(-50%,-50%);
        transform: translate(-50%,-50%);
    }
</style>

<script>
    function validateForm() {
        var key = $("#key").val();
        var lang = $("#lang_select").val();

        if (lang === "EN" && !/^[a-zA-Z]+$/.test(key)) {
            alert("Key must contain only letters from English alphabet");
            return false;
        } else if (lang === "RU" && !/^[а-яё]+$/i.test(key)) {
            alert("Key must contain only letters from Russian alphabet");
            return false;
        }

        return true;
    }
</script>

<div class="center">

    <div class="container">
        <h3 class="display-4">Choose file!</h3>

        <form method="post" enctype="multipart/form-data" onsubmit="return validateForm();">

            <div class="form-group">
                <input class="form-inline form-control-file"
                       id="file_input"
                       name="file"
                       required="required"
                       type="file"
                       accept=".txt,.docx" />

            </div>

            <div class="form-group">
                <label for="key" class="align-content-start">Enter cipher key:</label>
                <input class="form-control"
                       type="text"
                       name="cipherKey"
                       id="key"
                       required="required" />
            </div>

            <div class="form-group">
                <label for="lang_select">Choose language:</label>
                <select class="form-control"
                        name="lang"
                        id="lang_select"
                        title="Language letters from which are handled and not ignored">
                    <option value="EN"
                            title="Letters from English alphabet (26)">
                        English
                    </option>
                    <option value="RU"
                            title="Letters from Russian alphabet (33)">
                        Russian
                    </option>
                </select>
            </div>

            <div class="btn-group w-100">
                <button class="btn btn-outline-dark w-100"
                        asp-controller="Encrypt"
                        asp-action="Encrypt">Encrypt</button>
                <button class="btn btn-outline-dark w-100"
                        asp-controller="Encrypt"
                        asp-action="Decrypt">Decrypt</button>
            </div>

        </form>
    </div>

</div>

CryptoApp/CryptoApp/CryptoApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Vigenere fans' choice!";
    
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>to the world of cryptography</p>
    <a class="btn btn-outline-dark" 
            asp-area="" 
            asp-controller="Encrypt"
            asp-action="LoadFileForm">Start journey!</a>
</div>

CryptoApp/CryptoApp/CryptoApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CryptoApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CryptoApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Encrypt" asp-action="LoadFileForm">Encryption & decryption</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CryptoApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>